# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        exclude: ^.*-hook/src/.*/models.py$
        additional_dependencies: ['click==8.0.4']
  - repo: https://github.com/pycqa/flake8
    rev: '7.3.0'
    hooks:
      - id: flake8
        exclude: ^.*\.aws-sam.*$
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
        exclude: ^.*-hook/src/.*/models.py$
