name: Pre-Merge Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependancies
        run: pip install -r requirements.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Run tests
        run: python -m pytest test/ -v
